services:

  postgres:
    image: postgres:18
    container_name: saha-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - ./postgres_data:/var/lib/postgresql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  n8n:
    image: n8nio/n8n:latest
    container_name: saha-n8n
    restart: unless-stopped

    ports:
      - "7000:5678"

    environment:
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_HOST: localhost
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      N8N_EDITOR_BASE_URL: http://localhost:7000

      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE}
      TZ: ${TZ}

      N8N_SECURE_COOKIE: "false"

    volumes:
      - ./n8n_data:/home/node/.n8n

    depends_on:
      postgres:
        condition: service_healthy


  ollama:
    image: ollama/ollama:latest
    container_name: saha-ollama
    restart: unless-stopped

    ports:
      - "11434:11434"

    volumes:
      - ./ollama_data:/root/.ollama

    gpus: all
  neo4j:
    image: neo4j:5.26-community
    container_name: saha-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/saha_neo4j_password
    volumes:
      - ./neo4j_data:/data
      - ./neo4j_logs:/logs